Add hw1
VadimShabashov/itmo-2022-software-design pull request #1
Opened 2022-02-20 18:43 UTC by VadimShabashov

2022-04-15 19:20 UTC, FirstTimeInForever requested changes
По функционалу:
* Ваш шелл прекращает работу если команда получает на вход несуществующий путь. Например: `cat asd`. `-0.2`
* Не работает 
```
x=ex
y=it
$x$y
```
`-0.5`
* `'$x'` и `"$x"` не выполняются как команды (`x` необъявленная переменная). `-0.2`
* `wc` не принимает ввод через пайп от внешних процессов (`git status | wc`). Более того после этого папы ломаются вообще. `-0.2`
* Не работает `git status`. `-0.5`
* `cat README.md |` и `echo "` не считаются ошибками (ну или нужно обрабатывать так же как в bash). `-0.2`
* `cat` без аргументов не выводит ошибку или не работает как оригинал.

Вам нужно поправить замечания по коду/функционалу и добавить нормальный `README.md`. Еще было бы круто иметь адекватный `.editorconfig`.

`3.8/10`.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/parser/parser.py
> +    def check_assignments(parsed_string):
Функция которая называется `check_...` явно не должна делать чего-то кроме  самой проверки.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/main.py
> +        var_name, var_value = expression.split("=", maxsplit=1)  # Т.к. первый знак равенства отвечает за присваивание
Кажется это должно происходить внутри парсера.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/main.py
> +                    output, status = self.operation_getter.execute_operation(*args, name=operator, prev_output=output)
Что делать если `"описание ошибки"` будет равно `"exit""`? Строку стоит явно на что-то заменить. Возможно стоит завести какую-нибудь абстракцию для этого - `OperationStatus`, например. `-0.2`.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/main.py
> +        Запись результата может производиться как в stdout, так и в файл. Она производится построчно, поэтому если
Если  Вам тут приходит output stream, то кажется нет смысла писать про stdout или file. Может быть там вообще поток в сеть что-то пишет или посылает сигналы на другую планету.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/main.py
> +    def write_output(self, output, status):
А зачем вам вообще тут `status`?

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/main.py
> +    def __init__(self, input_stream=None, output_stream=None):
Почему по дефолту `None`? Логичнее было бы присваивать `stdin` и `stdout`.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/main.py
> +                if self.output_stream:
Чтобы не делать разные ветки для `stdout` и файлов, стоит сделать так чтобы всегда приходил валидный поток и писать в него. С точки зрения пользователя потока, Вам абсолютно не важно куда он пишет.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/main.py
> +                if self.output_stream:
Более того, в файлы вам кажется и не надо писать вообще...

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/operations/operations.py
> +        if len(args) == 0:
Лучше бы, конечно, разбить на несколько функций. Хотя бы этот if.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/operations/operations.py
> +class OperationGetter:
Раз он `отвечает за выполнение ... команды`, то логичнее было бы его назвать не `...Getter`, а `...Executor`)

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/operations/operations.py
> +    Класс отвечает за выполнение переданной в текстовом виде команды.
Вот это лучше делать не тут. Если, вдруг, кто-то захочет расширить ваш шелл добавлением новой команды, то ему придется менять код вашего `OperationGetter` (если расширить хочет консумер вашего кода, то он вообще не сможет поменять этот код). Логично было бы параметризовать ваш `OperationGetter` вот этим списком. По-факту у Вас получится [фабрика](https://refactoring.guru/design-patterns/factory-method) на минималках.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/operations/operations.py
> +            # Пробуем запустить процесс в терминале.
Я ничего не понял что тут написано. `vim` и друзья должны работать если просто перенаправлять потоки.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/operations/operations.py
> +            pattern = re.compile(f".+? {name}: not found\n")
Так, тут явно что-то нехорошее происходит. Конкретный формат `command not found` зависит от шела и платформы, что этот регэксп некорректен (более того, вы его при каждом вызове компилируете). Вам не нужно понимать нашелся ли бинарник или нет. Все что нужно сделать это проверить `exit code` и вывести `stdout`. `-1`.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/operations/operations.py
> +    def execute(*args, prev_output):
Вот тут было бы неплохо принимать не статическую строку с выводом, а поток. И точно так же вывод - принимать output поток и писать в него.

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/operations/operations.py
> +            process = subprocess.run([f"{name}", *args], shell=True, stderr=subprocess.PIPE)
А зачем `shell=True`?

2022-04-15 19:20 UTC, FirstTimeInForever commented on src/operations/operations.py
> +        return Path(__file__).resolve().parent.parent, ""
Выглядит очень странно. Сломается после первого рефакторинга в которым Вы переместите этот файл в другое место. Явно нужно на что-то заменить.

2022-04-15 19:20 UTC, FirstTimeInForever commented on test/parser/test_parser.py
> +def test_parse():
Так, нет. Тесты так не нужно писать. Обычно каждую проверку (в Вашем случае это `assert`ы) помещают в отдельный метод с __говорящим__ названием. Помимо очевидных преимуществ, у Вас будут запускаться __все__ тестовые сценарии вместо остановки на первом зафейленном (если Вы правильно используете тестовый фреймворк). `-2`.

2022-04-15 19:20 UTC, FirstTimeInForever commented on test/parser/test_parser.py
> +    parser = Parser({"a": '3', "b": '2'})
Инстанс парсера в каждый тест тоже нужен новый.

2022-04-15 19:20 UTC, FirstTimeInForever commented on test/parser/test_parser.py
> +    assert parser.parse("echo \'\"cats\"\' \"\'dogs\'\"") == ([['echo', '\"cats\"', '\'dogs\'']], False)
Было бы неплохо добавить тесты на некорректный синтаксис.

2022-04-15 19:20 UTC, FirstTimeInForever commented on test/operations/test_operations.py
> +def test_echo():
Маловато. Должны быть тесты на все команды. `-1`.

2022-04-15 19:20 UTC, FirstTimeInForever commented on README.md
> +* Start application with `python3 -m src.main` from project root directory.
А как запускать тесты?

2022-04-15 19:20 UTC, FirstTimeInForever commented on README.md
> +* Start application with `python3 -m src.main` from project root directory.
Какой версии нужен питон? Нужно описать требования к среде в которой нужно запускать ваше приложение.

2022-04-15 19:20 UTC, FirstTimeInForever commented on README.md
> +
Было бы неплохо добавить тут какое-нибудь описание - что это вообще такое. Стоит добавить про то какие команды поддерживает Ваш шелл и их синтаксис. Было бы круто хотя бы минимально описать архитектуру и общее устройство вашего приложения. Сюда же можно вставить картинку с Вашей диграммой. `-1`.

2022-04-15 19:20 UTC, FirstTimeInForever commented on README.md
> +* Start application with `python3 -m src.main` from project root directory.
Было бы неплохо еще что-то написать про `requirements.txt`)

2022-04-15 19:20 UTC, FirstTimeInForever commented on .github/workflows/python-ci.yml
> +        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
А зачем вам `treats all errors as warnings`? Казалось бы нужно именно обратное...

2022-04-15 19:20 UTC, FirstTimeInForever commented on .github/workflows/python-ci.yml
> +on:
Было бы неплохо запускать не только на `main`. Что делать без CI на feature бранчах, например? `-0.2`.

2022-04-17 12:52 UTC, merged

2022-04-20 16:43 UTC, VadimShabashov commented on src/parser/parser.py
> +    def check_assignments(parsed_string):
Исправил. `check_assignments` теперь только проверяет присваивания. Создал отдельную функцию, которая их выполняет.

2022-04-20 16:43 UTC, VadimShabashov commented on src/main.py
> +        var_name, var_value = expression.split("=", maxsplit=1)  # Т.к. первый знак равенства отвечает за присваивание
Исправил. Вынес это в парсер.

2022-04-20 16:45 UTC, VadimShabashov commented on src/main.py
> +                    output, status = self.operation_getter.execute_operation(*args, name=operator, prev_output=output)
Создал `ExecutionStatus`, который хранит предыдущий результат `prev_output`, флаг `exit`, ошибки `errors` и результат, который будет получен в текущей команде (`output`).

Эту абстракцию и передаю в пайплайне между командами.

2022-04-20 16:47 UTC, VadimShabashov commented on src/main.py
> +        Запись результата может производиться как в stdout, так и в файл. Она производится построчно, поэтому если
Перешел к работе со стримами. Для удобства создал объект `Stream`, который имеет методы `read` и `write`

2022-04-20 16:47 UTC, VadimShabashov commented on src/main.py
> +    def write_output(self, output, status):
Исправил.

2022-04-20 16:49 UTC, VadimShabashov commented on src/main.py
> +    def __init__(self, input_stream=None, output_stream=None):
Присваиваю теперь `stdin`. До этого считал, что вывод тоже нужно уметь делать в файл. Как я понял, это не нужно на самом деле, поэтому теперь `output_stream` фиксирован и равен `stdout`.

2022-04-20 16:49 UTC, VadimShabashov commented on src/main.py
> +                if self.output_stream:
Исправил это.

2022-04-20 16:50 UTC, VadimShabashov commented on src/main.py
> +                if self.output_stream:
Исправил. Пытался до этого сделать возможности как можно шире, но раз это не требуется, то лучше откажусь от этой идеи :)

2022-04-20 16:51 UTC, VadimShabashov commented on src/operations/operations.py
> +        if len(args) == 0:
Разбил на несколько функций.

2022-04-20 16:51 UTC, VadimShabashov commented on src/operations/operations.py
> +class OperationGetter:
Исправил.

2022-04-20 16:52 UTC, VadimShabashov commented on src/operations/operations.py
> +            pattern = re.compile(f".+? {name}: not found\n")
Исправил. Теперь просто ловлю ошибку, если она произошла, и печатаю ее.

2022-04-20 16:58 UTC, VadimShabashov commented on src/operations/operations.py
> +            # Пробуем запустить процесс в терминале.
В итоге пришел к такому выводу: если поддерживать "интерактивные команды" (`vim`, `nano`), то нельзя ловить вывод (т.к. там мусор + команда работает плохо, не в отдельном окошке). Если же там обычная команда (`git status`, ...), то вывод ловить надо, т.к. хочется уметь передавать его в пайплайне.

Единственное решение, которое придумал: разделить вручную команды интерактивные от обычных. Явно выделил для этого `vim` и `nano`; у них не ловлю вывод. Для всех остальных ловлю.

Это не очень хорошо, т.к. если вызвать какую-то другую интерактивную команду, то она будет работать плохо. Но тут нужно как-то уметь тогда отличать интерактивные команды от обычных.
Мне показалось, что это уже будет слишком сложно, поэтому пока оставил так.

В версии, что сделал, работают `vim`, `nano` и все неинтерактивные команды.

2022-04-20 16:59 UTC, VadimShabashov commented on src/operations/operations.py
> +    def execute(*args, prev_output):
Передаю теперь между командами абстракцию `ExecutionStatus`

2022-04-20 17:00 UTC, VadimShabashov commented on src/operations/operations.py
> +            process = subprocess.run([f"{name}", *args], shell=True, stderr=subprocess.PIPE)
Действительно, это не нужно. Убрал это.

2022-04-20 17:00 UTC, VadimShabashov commented on src/operations/operations.py
> +        return Path(__file__).resolve().parent.parent, ""
Исправлено (Иван исправил, когда реализовывал `cd`и `ls`)

2022-04-20 17:03 UTC, VadimShabashov commented on test/parser/test_parser.py
> +def test_parse():
Реализовал каждый `assert` отдельно в методе с нормальным названием. Вычитал, что еще полезно все добавлять в класс, поэтому теперь все методы тестирования для конкретной команды лежат в своем классе.

2022-04-20 17:04 UTC, VadimShabashov commented on test/parser/test_parser.py
> +    parser = Parser({"a": '3', "b": '2'})
Добавил его, как поле класса.

Из [документации](https://docs.pytest.org/en/7.1.x/getting-started.html#get-started): "Something to be aware of when grouping tests inside classes is that each test has a unique instance of the class."

То есть как раз у каждого метода будет свой инстанс парсера.

2022-04-20 17:05 UTC, VadimShabashov commented on test/parser/test_parser.py
> +    assert parser.parse("echo \'\"cats\"\' \"\'dogs\'\"") == ([['echo', '\"cats\"', '\'dogs\'']], False)
Добавил.

2022-04-20 17:05 UTC, VadimShabashov commented on test/operations/test_operations.py
> +def test_echo():
Реализовал тесты для всех команд.

2022-04-20 17:05 UTC, VadimShabashov commented on README.md
> +* Start application with `python3 -m src.main` from project root directory.
Добавил про это пункт в `README`

2022-04-20 17:05 UTC, VadimShabashov commented on README.md
> +* Start application with `python3 -m src.main` from project root directory.
Добавил про это пункт в `README`

2022-04-20 17:06 UTC, VadimShabashov commented on README.md
> +
Добавил `README`, где описал все команды, как запускать, привел примеры, привел описание архитектуры, и написал пару строк про требования.

2022-04-20 17:06 UTC, VadimShabashov commented on README.md
> +* Start application with `python3 -m src.main` from project root directory.
Написал.

2022-04-20 17:08 UTC, VadimShabashov commented on .github/workflows/python-ci.yml
> +        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
Убрал это.

У меня flake8 стал жаловаться на слишком сложный `grep` и `parser`. Поправлю их в следующем PR (чтобы было как исправление hw2)

2022-04-20 17:08 UTC, VadimShabashov commented on .github/workflows/python-ci.yml
> +on:
Исправил.

2022-04-20 17:13 UTC, VadimShabashov commented
1.  Исправил выполение  '$x' и "$x", как команд (теперь возвращает `$x: No such file or directory`)
2. Научил `wc` пользоваться пайпом (теперь можно в него передавать результаты `git status`
3. `git status` теперь работает
4. Пустой пайп (`echo cats | `) и незакрытая кавычка (`echo 'cats`) теперь бросают ошибку
5. `cat` без аргументов теперь выводит ошибку
6. Добавил `.editorconfig` и нормальный `README`