Add grep and tests
VadimShabashov/itmo-2022-software-design pull request #2
Opened 2022-03-24 18:54 UTC by VadimShabashov

Добавил команду grep и тесты для нее. Т.к. прошлое дз еще не проверили, то делаю PR в ветку hw1.

2022-04-15 19:41 UTC, FirstTimeInForever requested changes
По функционалу:
* `grep` не принимает пайпы `cat README.md | grep #`. `-1`

Опять же, стоит что-то написать про `grep` в `README.md` и пофиксить замечания из первого задания.

`6/10`.

2022-04-15 19:41 UTC, FirstTimeInForever commented on src/operations/operations.py
> +    def execute(*args, prev_output):
Функция почти на 100 строк. Было бы неплохо разбить на несколько отдельных функций.

2022-04-15 19:41 UTC, FirstTimeInForever commented on src/operations/operations.py
> +            pattern = re.compile(r"-[iwA]*")
Мало того что Вы этот регэксп компилируете при каждом вызове функции, так еще и в цикле! Обычно регэкспы компилируют один раз (можете сохранить как статическое поле).

2022-04-15 19:41 UTC, FirstTimeInForever commented on test/operations/test_operations.py
> +def test_grep(monkeypatch):
Маловато. Вы не тестируете все комбинации ключей. Ну и опять же, тесты так не пишут. `-3`.

2022-04-17 12:51 UTC, merged

2022-04-20 18:31 UTC, VadimShabashov commented on src/operations/operations.py
> +    def execute(*args, prev_output):
Разбил на несколько функций. Но все равно пришлось чуток повысить `max-complexity` в flake8, потому что жаловался.

2022-04-20 18:31 UTC, VadimShabashov commented on src/operations/operations.py
> +            pattern = re.compile(r"-[iwA]*")
Исправил. Компилирую, как статическое поле.

2022-04-20 18:32 UTC, VadimShabashov commented on test/operations/test_operations.py
> +def test_grep(monkeypatch):
Добавил тестов на каждый из ключей. Переписал тесты так, чтобы каждый `assert` был в своем методе.

2022-04-20 18:34 UTC, VadimShabashov commented
1. Исправил передачу пайпа в `grep`. Теперь можно писать `echo file_name | grep word` и все работает.
2. Поправил текст ошибок, которые выводит `grep`
3. Добавил `grep` в `README`